config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :employees do
    resources :attendances, only: [:index, :new, :create]
    resources :leaves, only: [:index, :new, :create, :update]
    resources :organizations, only: [:index, :new, :create]
    resources :work_from_homes, only: [:index, :new, :create, :update]
  end

end

app/models/leave.rb
class Leave < ApplicationRecord
  include Filterable

  # Override inheritance_column to avoid STI issues with the 'type' column
  self.inheritance_column = nil

  belongs_to :user

  enum type: { casual: 0, sick: 1 }
  enum status: { not_approved: 0, approved: 1 }

  validates :date, presence: true, uniqueness: { scope: :user_id, message: 'You have already applied leave for this date.' } 

  scope :filter_by_type, -> (type) { where(type: type) }
  scope :filter_by_status, -> (status) { where(status: status) }
  scope :filter_by_date, -> (order) { order(date: order) }
  scope :filter_by_name, -> (order) { joins(:user).order("users.name #{order}") }

end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  include Filterable

  before_action :set_leave, only: [:update]

  def index
    @leaves = policy_scope(Leave)
    @leaves = Leave.filter(filtering_params) if current_user.manager?
    authorize @leaves
  end

  def new
    @leave = current_user.leaves.new
    authorize @leave
  end

  def create
    @leave = current_user.leaves.new(leave_params)
    authorize @leave

    respond_to do |format|
      if @leave.save
        format.html { redirect_to employee_leaves_path, notice: 'Leave applied successfully!' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('leave_form', partial: 'shared/success_message',
          locals: { message: 'Leave applied successfully!', redirect_path: employee_leaves_path(current_user) })
        end
      else
        format.html do
          flash[:alert] = @leaves.errors.full_messages
          render :new
        end
        format.turbo_stream do
          render turbo_stream: turbo_stream.append('leave_form', partial: 'shared/flash_message', 
          locals: { message: @leave.errors.full_messages })
        end
      end
    end
  end

  def update
    authorize @leave

    if @leave.update( status: :approved )
      redirect_to employee_leaves_path, notice: 'Leave approved successfully!'
    else
      redirect_to employee_leaves_path, alert: @leave.errors.full_messages.join(", ")
    end
  end

  private

  def set_leave
    @leave =  if current_user.manager?
                Leave.find(params[:id])
              else
                current_user.leaves.find(params[:id])
              end

    authorize @leave
  end

  def leave_params
    params.require(:leave).permit(:date, :type)
  end

  def filtering_params
    params.slice(:type, :status, :date, :name)
  end

end

app/helpers/leave_helper.rb
module LeaveHelper
  def leave_table_headers
    if current_user.manager?
      ['Name', 'Role', 'Day', 'Date', 'Type', 'Status', 'Update']
    else
      ['Day', 'Date', 'Type', 'Status']
    end
  end

  def leave_table_rows
    @leaves.map do |leave| 
      if current_user.manager?
        [
          
          { content: leave.user.name },
          { content: leave.user.role.humanize },
          { content: leave.date.strftime('%A') },
          { content: leave.date.strftime('%d/%m/%Y') },
          { content: leave.type.humanize },
          { content: leave.status.humanize, class: leave.not_approved? ? 'text-red-600' : 'text-green-600' },
          { content: leave.not_approved? ? 
                        button_to('Approve', employee_leave_path(leave.user.id, leave.id), method: :patch, 
                        class: 'custom-btn', 
                        form: { data: { turbo_confirm: 'Are you sure you want to approve this leave?' } }) :
                        link_to('Approved', '#', class: 'px-3 py-2 text-sm text-white rounded-2xl bg-neutral-700 cursor-default', disabled: true)
          }
        ]
      else
        [
          { content: leave.date.strftime('%A') },
          { content: leave.date.strftime('%d/%m/%Y') },
          { content: leave.type.humanize },
          { content: leave.status.humanize, class: leave.not_approved? ? 'text-red-600' : 'text-green-600' },
        ]
      end
    end
  end
end

app/views/leaves/_apply_leave_button.html.erb
<% if !current_user.manager? %>
  <%= link_to "Apply Leave", new_employee_leave_path(current_user.id), class: 'custom-btn' %>
<% end %>

app/views/leaves/_form.html.erb
<%= form_with(model: leave, url: employee_leaves_path, local: true) do |form| %>
  <div class="mb-4">
    <%= form.label :date, class: 'block text-sm font-medium text-gray-700' %>
    <%= form.date_field :date, min: Date.today, class: 'mt-1 block w-full border-gray-300 rounded-md shadow-sm cursor-pointer' %>
  </div>

  <div class="mb-4">
    <%= form.label :type, class: 'block text-sm font-medium text-gray-700' %>
    <%= form.select :type, Leave.types.keys.map { |type| [type.humanize, type] }, {},
        class: 'mt-1 block w-full border-gray-300 rounded-md shadow-sm'
     %>
  </div>

  <div class="flex items-center justify-end space-x-4">
    <%= form.submit 'Apply', class: 'submit-btn' %>
    <%= link_to 'Cancel', employee_leaves_path, class: 'cancel-btn', data: {turbo_frame: "_top"} %>
  </div>  
<% end %>

<%= render 'shared/error_message', model: leave %>

app/views/leaves/index.html.erb
<div class="mt-20 ml-64 px-3 py-1">
  <div class="flex items-center justify-between">
    <p class="text-2xl font-bold">Leaves Records</p>
    <%= render 'apply_leave_button' %>
  </div>

  <hr class="my-4">

  <% if current_user.manager? %>
    <%= turbo_frame_tag "filters" do %>
      <%= render 'shared/filters', url: employee_leaves_path, model: 'Leave' %>
    <% end %>  
  <% end %>

  <%= turbo_frame_tag "list" do %>
    <%= render 'shared/records_table', headers: leave_table_headers, rows: leave_table_rows %>
  <% end %>

</div>

app/views/leaves/new.html.erb
<div class="mt-20 ml-64 px-3 py-1">
  <div class="mb-6">
    <h2 class="text-2xl font-semibold text-gray-800">Apply For Leave</h2>
    <hr class="mt-2">
  </div>

  <%= turbo_frame_tag 'leave_form' do %>
    <%= render 'form', leave: @leave %>
  <% end %>

  <%= render 'shared/error_message', model: @leave %>
</div>