config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :employees do
    resources :attendances, only: [:index, :new, :create]
    resources :leaves, only: [:index, :new, :create, :update]
    resources :organizations, only: [:index, :new, :create]
    resources :work_from_homes, only: [:index, :new, :create, :update]
  end

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'

  validates :name, presence: true
  validates :creator_id, presence: true
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all
    authorize @organizations
  end

  def new
    @organization = Organization.new
    authorize @organization
  end

  def create
    @organization = Organization.new(organization_params)
    @organization.creator_id = current_user.id

    authorize @organization

    if @organization.save
      redirect_to employee_organizations_path, notice: 'Organization was successfully created.'
    else
      flash.now[:alert] = @organization.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, url: employee_organizations_path, local: true) do |form| %>
  <div class="mb-4">
    <%= form.label :name, class: "font-bold" %><br />
    <%= form.text_field :name, class: "rounded-lg w-50 p-1", required: true %>
  </div>

  <div class="flex items-center justify-end space-x-4">
    <%= form.submit 'Apply', class: 'submit-btn' %>
    <%= link_to 'Cancel', employee_organizations_path, class: 'cancel-btn' %>
  </div>
<% end %>

<%= render 'shared/error_message', model: organization %>

app/views/organizations/index.html.erb
<div class="mt-20 ml-64 px-3 py-1">
  <div class="flex items-center justify-between">
    <p class="text-2xl font-bold">All Organizations</p>
    <%= link_to "Add Organization", new_employee_organization_path(current_user.id), class: 'custom-btn' %>
  </div>
  <hr class="my-4">

  <% headers = ['ID', 'Name'] %>

  <% rows = @organizations.each_with_index.map do |organization, index| 
    [
      { content: index + 1 },
      { content: organization.name }
    ]
  end %>

<%= render 'shared/records_table', headers: headers, rows: rows %>
</div>
  

app/views/organizations/new.html.erb
<div class="mt-20 ml-64 px-3 py-1">
  <div class="mb-6">
    <h2 class="text-2xl font-semibold text-gray-800">Create a new Organization</h2>
    <hr class="mt-2">
  </div>

  <%= render 'form', organization: @organization %>

  <%= render 'shared/error_message', model: @organization %>
</div>