config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :employees do
    resources :attendances, only: [:index, :new, :create]
    resources :leaves, only: [:index, :new, :create, :update]
    resources :organizations, only: [:index, :new, :create]
    resources :work_from_homes, only: [:index, :new, :create, :update]
  end

end

app/models/work_from_home.rb
class WorkFromHome < ApplicationRecord
  include Filterable

  belongs_to :user

  enum status: { not_approved: 0, approved: 1 }

  validates :date, presence: true, uniqueness: { scope: :user_id, message: 'You have already applied WFH for this date.' }

  scope :filter_by_status, -> (status) { where(status: status) }
  scope :filter_by_date, -> (order) { order(date: order) }
  scope :filter_by_name, -> (order) { joins(:user).order("users.name #{order}") }

  before_create :limit_count

  def limit_count
    start_date = 2.months.ago(self.date)
    count = self.class.where(user: self.user)
              .where(status: :approved)
              .where('date >= ? AND date <= ?', start_date, self.date)
              .count

    return if count < 2

    errors.add(:base, "Cannot apply for more WFH as you already have 2 in the previous two months.")
    throw(:abort)
  end

end

app/controllers/work_from_home_controller.rb
class WorkFromHomeController < ApplicationController
  include Filterable

  before_action :set_wfh, only: [:update]

  def index
    @work_from_homes = policy_scope(WorkFromHome)
    @work_from_homes = WorkFromHome.filter(filtering_params)  if current_user.manager?
    authorize @work_from_homes
  end

  def new
    @work_from_home = current_user.work_from_homes.new
    authorize @work_from_home
  end

  def create
    @work_from_home = current_user.work_from_homes.new(wfh_params)
    authorize @work_from_home
  
    respond_to do |format|
      if @work_from_home.save
        format.html { redirect_to employee_work_from_homes_path, notice: 'Work From Home request applied successfully!' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('wfh_form', partial: 'shared/success_message', 
          locals: { message: 'Work From Home applied successfully!', redirect_path: employee_work_from_homes_path(current_user) })
        end
      else
        format.html { render :new }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('wfh_form', partial: 'work_from_home/form', 
          locals: { messages: @work_from_home.errors.full_messages })
        end
      end
    end
  end

  def update
    authorize @work_from_home

    if @work_from_home.update(status: 'approved')
      redirect_to employee_work_from_homes_path, notice: 'Work From Home request approved successfully!'
    else
      redirect_to employee_work_from_homes_path, alert: @work_from_home.errors.full_messages.join(", ")
    end
  end

  private

  def set_wfh
    @work_from_home =  WorkFromHome.find(params[:id])
  end

  def wfh_params
    params.require(:work_from_home).permit(:date)
  end

  def filtering_params
    params.slice(:status, :date, :name)
  end

end

app/helpers/work_from_home_helper.rb
module WorkFromHomeHelper
  def wfh_table_headers
    if current_user.manager?
      ['Name', 'Role', 'Day', 'Date', 'Status', 'Update']
    else
      ['Day', 'Date', 'Status']
    end
  end

  def wfh_table_rows
    @work_from_homes.map do |wfh| 
      if current_user.manager?
        [
          { content: wfh.user.name },
          { content: wfh.user.role.humanize },
          { content: wfh.date.strftime('%A') },
          { content: wfh.date.strftime('%d/%m/%Y') },
          { content: wfh.status.humanize, class: wfh.not_approved? ? 'text-red-600' : 'text-green-600' },
          { content: wfh.not_approved? ? 
            button_to('Approve', employee_work_from_home_path(wfh.user.id, wfh.id), method: :patch, 
                      class: 'custom-btn', 
                      form: { data: { turbo_confirm: 'Approve WFH request?' } }) : 
            link_to('Approved', '#', class: 'custom-disabled-btn', disabled: true)
          }
        ]
      else  
        [
          { content: wfh.date.strftime('%A') },
          { content: wfh.date.strftime('%d/%m/%Y') },
          { content: wfh.status.humanize, class: wfh.not_approved? ? 'text-red-600' : 'text-green-600' },
        ]
      end
    end
  end
end

app/views/work_from_home/_apply_wfh_button.html.erb
<% if !current_user.manager? %>
  <%= link_to "Apply WFH", new_employee_work_from_home_path(current_user.id), class: 'custom-btn' %>
<% end %>

app/views/work_from_home/_form.html.erb
<%= form_with(model: @work_from_home, url: employee_work_from_homes_path, local: true) do |form| %>
  <div class="mb-4">
    <%= form.label :date, class: 'block text-sm font-medium text-gray-700' %>
    <%= form.date_field :date, class: 'mt-1 block w-full border-gray-300 rounded-md shadow-sm cursor-pointer', min: Date.current %>
  </div>

  <div class="flex items-center justify-end space-x-4">
    <%= form.submit 'Apply', class: 'submit-btn' %>
    <%= link_to 'Cancel', employee_work_from_homes_path, class: 'cancel-btn', data: {turbo_frame: "_top"} %>
  </div>
<% end %>

<%= render 'shared/error_message', model: @work_from_home %>

app/views/work_from_home/index.html.erb
<div class="mt-20 ml-64 px-3 py-1">
  <div class="flex items-center justify-between">
    <p class="text-2xl font-bold">Work From Home Records</p>
    <%= render 'apply_wfh_button' %>
  </div>

  <hr class="my-4">

  <% if current_user.manager? %>
    <%= turbo_frame_tag "filters" do %>
      <%= render 'shared/filters', url: employee_work_from_homes_path %>
    <% end %>  
  <% end %>

  <%= turbo_frame_tag "list" do %>
    <%= render 'shared/records_table', headers: wfh_table_headers, rows: wfh_table_rows %>
  <% end %>

</div>

app/views/work_from_home/new.html.erb
<div class="mt-20 ml-64 px-3 py-1">
  <div class="mb-6">
    <h2 class="text-2xl font-semibold text-gray-800">Apply For WFH</h2>
    <hr class="mt-2">
  </div>

  <%= turbo_frame_tag 'wfh_form' do %>
    <%= render 'form', work_from_home: @work_from_home %>
  <% end %>

  <%= render 'shared/error_message', model: @work_from_home %>

</div>