config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :employees do
    resources :attendances, only: [:index, :new, :create]
    resources :leaves, only: [:index, :new, :create, :update]
    resources :organizations, only: [:index, :new, :create]
    resources :work_from_homes, only: [:index, :new, :create, :update]
  end

end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  enum status: { absent: 0, present: 1 }

  validates :date, presence: true
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance_today, only: [:index, :new]
  before_action :check_attendance_marked, only: [:new, :create]

  def index
    @attendances = policy_scope(Attendance)
    authorize @attendances
  end

  def new
    @attendance = current_user.attendances.new(date: Date.current)
    authorize @attendance
  end
  
  def create
    @attendance = current_user.attendances.new(attendance_params)
    @attendance.date = Date.current
    authorize @attendance

    if @attendance.saveq
      redirect_to employee_attendances_path(current_user), notice: 'Attendance marked successfully.'
    else
      flash.now[:alert] = @attendance.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def attendance_params
    params.require(:attendance).permit(:status)
  end

  def set_attendance_today
    @attendance_today = current_user.attendances.find_by(date: Date.current)
  end

  def check_attendance_marked
    if @attendance_today.present?
      redirect_to employee_attendances_path(current_user), alert: "You have already marked attendance for today."
    end
  end
end

app/helpers/attendance_helper.rb
module AttendanceHelper
  def attendance_table_headers
    if current_user.manager?
      ['Name', 'Role', 'Day', 'Date', 'Status']
    else
      ['Day', 'Date', 'Status']
    end
  end

  def attendance_table_rows
    @attendances.map do |attendance|
      if current_user.manager?
        [
          { content: attendance.user.name },
          { content: attendance.user.role.humanize },
          { content: attendance.date.strftime('%A') },
          { content: attendance.date.strftime('%d/%m/%Y') },
          { content: attendance.status, class: attendance.present? ? 'text-green-600' : 'text-red-600' }
        ]
      else
        [
          { content: attendance.date.strftime('%A') },
          { content: attendance.date.strftime('%d/%m/%Y') },
          { content: attendance.status, class: attendance.present? ? 'text-green-600' : 'text-red-600' }
        ]
      end
    end
  end
end

app/views/attendances/_mark_attendance_button.html.erb
<% if !current_user.manager? %>
  <% if @attendance_today %>
    <button class="custom-disabled-btn" disabled> Mark Attendance</button>
  <% else %>
    <%= link_to "Mark Attendance", new_employee_attendance_path(current_user), class: 'custom-btn' %>
  <% end %> 
<% end %>

app/views/attendances/index.html.erb
<div class="mt-20 ml-64 px-3 py-1">
  <div class="flex items-center justify-between">
    <p class="text-2xl font-bold">Attendance Records</p>
    <%= render 'mark_attendance_button' %>
  </div>

  <hr class="my-4">

  <%= render 'shared/records_table', headers: attendance_table_headers, rows: attendance_table_rows %>
</div>

app/views/attendances/new.html.erb
<div class="mt-20 ml-64 px-3 py-1">

  <div class="mb-6">
    <h2 class="text-2xl font-semibold text-gray-800">Mark Attendance</h2>
    <hr class="mt-2">
  </div>

  <%= form_with(model: @attendance, url: employee_attendances_path, local: true, class: "space-y-4") do |form| %>
    <div class="grid grid-cols-1 gap-6">
      <div>
        <%= form.label :day, "Day:", class: "block text-md font-medium text-gray-700" %>
        <%= form.text_field :date, value: @attendance.date.strftime('%A'), readonly: true, class: 'readonly-input-field' %>
      </div>
      <div>
        <%= form.label :date, "Date:", class: "block text-md font-medium text-gray-700" %>
        <%= form.text_field :date, value: @attendance.date, readonly: true, class: 'readonly-input-field' %>
      </div>
      <div class="flex items-center">
        <span class="text-gray-700 mr-2">Mark Present: </span>
        <%= form.check_box :status, { checked: @attendance.status == 'present' }, 'present', 'absent' %>
      </div>
    </div>

    <div class="flex justify-end space-x-4">
      <%= form.submit "Submit", class: 'inline-flex items-center p-2 text-md font-medium rounded-md text-white bg-green-600 hover:bg-green-700 cursor-pointer' %>
      <%= link_to "Cancel", employee_attendances_path, class: 'inline-flex items-center p-2 text-md font-medium rounded-md text-white bg-red-600 hover:bg-red-700' %>
    </div>
  <% end %>
</div>

app/views/attendances/show.html.erb
<div>show page</div>